#Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

    Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

In [0]:
import numpy as np  

In [0]:
a = np.array([1, 2, 3, 4])

In [0]:
b = np.array([4])

In [4]:
a+b

array([5, 6, 7, 8])

In [5]:
a.shape

(4,)

In [6]:
b.shape

(1,)

In [0]:
a = np.array([[0,0],[0,1]])

In [8]:
a

array([[0, 0],
       [0, 1]])

In [9]:
a.shape

(2, 2)

In [12]:
a + b

array([[4, 4],
       [4, 5]])

In [0]:
b = b.reshape(1,1)

In [11]:
a + b

array([[4, 4],
       [4, 5]])